# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Make.create([
    {company_name: "Acura", company_image: "https://image.pngaaa.com/767/698767-middle.png"},
    {company_name: "Alfa Romeo", company_image: "https://cdn.freelogovectors.net/wp-content/uploads/2018/03/alfa-romeo-logo-new.png"},
    {company_name: "Aston Martin", company_image: "https://toppng.com/uploads/preview/aston-martin-logo-vector-11573990512sjuo7dfmhh.png"},
    {company_name: "Audi", company_image: "https://seeklogo.com/images/A/Audi-logo-ED84DFE2E3-seeklogo.com.png"},
    {company_name: "Bentley", company_image: "https://cdn.worldvectorlogo.com/logos/bentley.svg"},
    {company_name: "BMW", company_image: "https://seeklogo.com/images/B/bmw-logo-248C3D90E6-seeklogo.com.png"},
    {company_name: "Bugatti", company_image: "https://seeklogo.com/images/B/Bugatti-logo-9B69E86879-seeklogo.com.png"},
    {company_name: "Buick", company_image: "https://seeklogo.com/images/B/Buick-logo-74DF4BAA11-seeklogo.com.png"},
    {company_name: "Cadillac", company_image: "https://seeklogo.com/images/C/cadillac-logo-01876B3913-seeklogo.com.png"},
    {company_name: "Chevrolet", company_image: "https://cdn.freelogovectors.net/wp-content/uploads/2018/04/Chevrolet-logo.png"},
    {company_name: "Chrysler ", company_image: "https://cdn.freelogovectors.net/wp-content/uploads/2018/03/chrysler-logo-500x103.png"},
    {company_name: "Datsun", company_image: "https://upload.wikimedia.org/wikipedia/commons/f/f8/Datsun_logo.png"},
    {company_name: "Delorean", company_image: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/DeLorean_Motor_Company_logo.svg/2560px-DeLorean_Motor_Company_logo.svg.png"},
    {company_name: "Dodge", company_image: "https://cdn.cdnlogo.com/logos/d/62/dodge-black.svg"},
    {company_name: "Ferrari", company_image: "https://seeklogo.com/images/F/ferrari-logo-7935CF173C-seeklogo.com.png"},
    {company_name: "FIAT", company_image: "https://seeklogo.com/images/F/Fiat_2007_Punto-logo-F856D851E3-seeklogo.com.png"},
    {company_name: "Ford", company_image: "https://logodownload.org/wp-content/uploads/2014/02/ford-logo-1-1.png"},
    {company_name: "GMC", company_image: "https://logodownload.org/wp-content/uploads/2019/08/gmc-logo.png"},
    {company_name: "Honda", company_image: "https://brandlogos.net/wp-content/uploads/2022/04/honda_motor-logo-brandlogos.net_.png"},
    {company_name: "Hummer", company_image: "https://cdn.worldvectorlogo.com/logos/hummer-logo.svg"},
    {company_name: "Hyundai", company_image: "https://seeklogo.com/images/H/Hyundai-logo-C41591E6EF-seeklogo.com.png"},
    {company_name: "INFINITI", company_image: "https://seeklogo.com/images/I/Infiniti-logo-38881263DA-seeklogo.com.png"},
    {company_name: "Isuzu", company_image: "https://cdn.cdnlogo.com/logos/i/10/isuzu.svg"},
    {company_name: "Jaguar", company_image: "https://seeklogo.com/images/J/Jaguar-logo-ED7E01A4A1-seeklogo.com.png"}, 
    {company_name: "Jeep", company_image: "https://seeklogo.com/images/J/Jeep-logo-E7EF700A70-seeklogo.com.png"},
    {company_name: "Kia", company_image: "https://brandslogos.com/wp-content/uploads/images/kia-motors-logo-vector.svg"},
    {company_name: "Lamborghini", company_image: "https://banner2.cleanpng.com/20180618/yw/kisspng-lamborghini-jaguar-cars-volkswagen-land-rover-5b273188330473.246860931529295240209.jpg"},
    {company_name: "Land Rover", company_image: "https://seeklogo.com/images/L/land-rover-logo-86296C9BE7-seeklogo.com.png"},
    {company_name: "Lexus", company_image: "https://seeklogo.com/images/L/Lexus-logo-A6EDA1B5EB-seeklogo.com.png"},
    {company_name: "Lincoln", company_image: "https://seeklogo.com/images/L/Lincoln-logo-0C5DC906F9-seeklogo.com.png"},
    {company_name: "Lotus", company_image: "https://seeklogo.com/images/L/Lotus__cars_-logo-BE19A562FB-seeklogo.com.png"},
    {company_name: "Maserati", company_image: "https://seeklogo.com/images/M/Maserati-logo-B1F381987A-seeklogo.com.png"},
    {company_name: "Maybach", company_image: "https://seeklogo.com/images/M/Maybach-logo-1D526C3598-seeklogo.com.png"},
    {company_name: "Mclaren", company_image: "https://images-wixmp-ed30a86b8c4ca887773594c2.wixmp.com/f/11de6924-bff6-4223-9e8e-a749bf67519f/d8ushqy-2e90bc97-a51e-450c-ba5e-a8296992d637.png?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1cm46YXBwOjdlMGQxODg5ODIyNjQzNzNhNWYwZDQxNWVhMGQyNmUwIiwiaXNzIjoidXJuOmFwcDo3ZTBkMTg4OTgyMjY0MzczYTVmMGQ0MTVlYTBkMjZlMCIsIm9iaiI6W1t7InBhdGgiOiJcL2ZcLzExZGU2OTI0LWJmZjYtNDIyMy05ZThlLWE3NDliZjY3NTE5ZlwvZDh1c2hxeS0yZTkwYmM5Ny1hNTFlLTQ1MGMtYmE1ZS1hODI5Njk5MmQ2MzcucG5nIn1dXSwiYXVkIjpbInVybjpzZXJ2aWNlOmZpbGUuZG93bmxvYWQiXX0.TkZloxDxtcFHj--hng18N8Rh5W7vYRTNgXmLztfxUWQ"},
    {company_name: "Mazda", company_image: "https://seeklogo.com/images/M/Mazda-logo-CC1CF9FB16-seeklogo.com.png"},
    {company_name: "Mercedes-Benz", company_image: "https://seeklogo.com/images/M/mercedes-benz-logo-0DCE214555-seeklogo.com.png"},
    {company_name: "MINI", company_image: "https://seeklogo.com/images/M/mini-cooper-logo-2B30B836FE-seeklogo.com.png"},
    {company_name: "Mitsubishi", company_image: "https://seeklogo.com/images/M/mitsubishi-logo-67EA251D5A-seeklogo.com.png"},
    {company_name: "Nissan", company_image: "https://seeklogo.com/images/N/Nissan-logo-4B3C580C8A-seeklogo.com.png"},
    {company_name: "Pagani", company_image: "https://www.logo.wine/a/logo/Pagani_(company)/Pagani_(company)-Logo.wine.svg"},
    {company_name: "Peugeot", company_image: "https://seeklogo.com/images/P/peugeot-logo-BF5B2383EF-seeklogo.com.png"},
    {company_name: "Polestar", company_image: "https://seeklogo.com/images/P/polestar-logo-888A52FA27-seeklogo.com.png"},
    {company_name: "Pontiac", company_image: "https://seeklogo.com/images/P/Pontiac-logo-59F67011F7-seeklogo.com.png"},
    {company_name: "Porsche", company_image: "https://seeklogo.com/images/P/porsche-logo-5995000C95-seeklogo.com.png"},
    {company_name: "Ram", company_image: "https://brandlogos.net/wp-content/uploads/2017/01/dodge-ram-logo.png"},
    {company_name: "Rolls Royce", company_image: "https://logoeps.com/wp-content/uploads/2011/05/rolls-royce-logo.png"},
    {company_name: "Saab", company_image: "https://seeklogo.com/images/S/Saab_MY2001-logo-3682B9389D-seeklogo.com.png"},
    {company_name: "Saleen", company_image: "https://download.logo.wine/logo/Saleen/Saleen-Logo.wine.png"},
    {company_name: "Saturn", company_image: "https://seeklogo.com/images/S/Saturn-logo-2A9D1264E7-seeklogo.com.png"},
    {company_name: "Scion", company_image: "https://seeklogo.com/images/S/Scion-logo-5A24E959D1-seeklogo.com.png"},
    {company_name: "Smart", company_image: "https://brandlogos.net/wp-content/uploads/2021/11/smart_car-brandlogo.net_.png"},
    {company_name: "Subaru", company_image: "https://cdn.freelogovectors.net/wp-content/uploads/2018/04/subaru-logo_freelogovectors.net_-500x281.png"},
    {company_name: "Tesla", company_image: "https://download.logo.wine/logo/Tesla%2C_Inc./Tesla%2C_Inc.-Logo.wine.png"},
    {company_name: "Toyota", company_image: "https://seeklogo.com/images/T/toyota-logo-239F6C9C1A-seeklogo.com.png"},
    {company_name: "Volkswagen", company_image: "https://seeklogo.com/images/V/Volkswagen-logo-80097D61AA-seeklogo.com.png"},
    {company_name: "Volvo", company_image: "https://seeklogo.com/images/V/volvo-logo-C0F7715FCB-seeklogo.com.png"}
])
